// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build corpushelper

// Bootstraps a minimal canonical fixture file for every registered
// rule that doesn't yet have one in tests/corpus/. The file gets:
//
//   - a banner comment naming the rule
//   - the "Example: X → Y" lines extracted from RuleInfo.Description
//     (one fixture each; expected computed via mask.Apply for safety)
//   - the trailing "# === generated ===" placeholder
//
// This is a SCAFFOLD only — every rule still needs a hand-curated
// canonical pass that adds tens of additional inputs from the BDD
// feature files and unit tests. This tool exists to make TestCorpusCompleteness
// pass quickly so the generator scaffold can be built and exercised.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/axonops/mask"
)

const (
	corpusDir       = "tests/corpus"
	canonicalBanner = "# === canonical (hand-written; preserved by generator) ==="
	generatedBanner = "# === generated (do not edit; regenerated by make corpus-regen) ==="
)

// exampleRE finds "Example: <input> → <output>" or "Example: <input> -> <output>"
// inside a description. It is intentionally permissive — descriptions
// vary in punctuation across rules.
var exampleRE = regexp.MustCompile(`(?:Example|Examples): ([^→]+?)(?:→|->)\s*([^.]+?)\.`)

func main() {
	for _, name := range sortedRules() {
		path := filepath.Join(corpusDir, name+".txt")
		if _, err := os.Stat(path); err == nil {
			continue // file already exists; do not overwrite
		}
		info, ok := mask.Describe(name)
		if !ok {
			fmt.Fprintf(os.Stderr, "warn: %s not describable; skipping\n", name)
			continue
		}
		body := buildFile(name, info)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", path, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s\n", path)
	}
}

func sortedRules() []string {
	names := mask.Rules()
	sort.Strings(names)
	return names
}

func buildFile(name string, info mask.RuleInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", canonicalBanner)
	fmt.Fprintln(&b, "#")
	fmt.Fprintf(&b, "# Rule: %s\n", name)
	if info.Category != "" {
		fmt.Fprintf(&b, "# Category: %s\n", info.Category)
	}
	if info.Jurisdiction != "" {
		fmt.Fprintf(&b, "# Jurisdiction: %s\n", info.Jurisdiction)
	}
	fmt.Fprintln(&b, "#")
	// Word-wrap the description at ~70 columns for readability.
	for _, line := range wrap(info.Description, 70) {
		fmt.Fprintf(&b, "# %s\n", line)
	}
	fmt.Fprintln(&b)
	// Pin every documented Example: from the description.
	added := 0
	for _, m := range exampleRE.FindAllStringSubmatch(info.Description, -1) {
		input := strings.TrimSpace(m[1])
		// Drop a leading "input was " or trailing "; the spec keeps it brief.
		input = strings.TrimSuffix(strings.TrimSpace(input), ":")
		// Skip placeholder examples like "(empty string)" or "anything".
		if input == "" || input == "(empty)" {
			continue
		}
		docExpected := strings.TrimSpace(m[2])
		actual := mask.Apply(name, input)
		// Warn loudly when the documented example disagrees with what
		// mask.Apply currently produces. The corpus locks current
		// behaviour, so a silent override here would hide a real
		// drift between the rule and its godoc.
		if docExpected != "" && docExpected != actual {
			fmt.Fprintf(os.Stderr,
				"%s: documented example %q → %q disagrees with mask.Apply output %q — locking the latter\n",
				name, input, docExpected, actual)
		}
		fmt.Fprintf(&b, "%s\t%s\n", input, actual)
		added++
	}
	if added == 0 {
		// Some descriptions don't have a parseable Example: clause.
		// Pin a safe empty-input fixture as a placeholder; subsequent
		// hand-curation will expand this.
		fmt.Fprintln(&b, "# TODO(#54): hand-curate canonical fixtures for this rule.")
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, generatedBanner)
	return b.String()
}

func wrap(s string, width int) []string {
	words := strings.Fields(s)
	var out []string
	var line strings.Builder
	for _, w := range words {
		if line.Len() == 0 {
			line.WriteString(w)
			continue
		}
		if line.Len()+1+len(w) > width {
			out = append(out, line.String())
			line.Reset()
			line.WriteString(w)
			continue
		}
		line.WriteByte(' ')
		line.WriteString(w)
	}
	if line.Len() > 0 {
		out = append(out, line.String())
	}
	return out
}
