// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build corpus

// Package corpus_test runs the bulk fixture corpus against every
// registered masking rule. One .txt file per rule, one fixture per
// line, tab-separated (input<TAB>expected). Lines starting with '#'
// and blank lines are ignored.
//
// # File format
//
//   - UTF-8, LF line endings, no BOM.
//   - Each fixture line MUST contain exactly one TAB. The first field
//     is the input; the second is the expected mask.Apply output.
//   - Empty input or empty expected is allowed (e.g. "\t" pins the
//     "" → "" contract). To avoid editors silently stripping trailing
//     whitespace, fixtures with an empty expected field must use the
//     `# corpus: escaped` pragma and write `\x00`-style explicit empty.
//     The simpler way to pin an empty expected is to write `\t` and
//     let the harness treat it as the empty string — that case is
//     covered by an explicit pragma check below.
//   - Pragmas appear as comment lines anywhere in the file:
//     `# corpus: escaped`  — enables escape decoding for the rest of
//     the file. Supported escapes: \\ \t \n \r \xNN \uXXXX. Truncated
//     or malformed escapes fail the test loudly with file:line:col.
//
// # Sections
//
// A fixture file may contain two sections delimited by comment
// banners:
//
//	# === canonical (hand-written; preserved by generator) ===
//	...
//	# === generated (do not edit; regenerated by make corpus-regen) ===
//	...
//
// The generator at tests/corpus/gen/ preserves everything above the
// `# === generated ===` banner verbatim and rewrites everything below
// it. Hand-curated fixtures go in the canonical section; the rest
// comes from the generator.
//
// # How to run
//
//	make test-corpus          # one-off
//	make check                # part of the full quality gate
//
// `go test ./...` does NOT run corpus tests — they sit behind the
// `corpus` build tag.
package corpus_test

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/axonops/mask"
)

const (
	// corpusDir is the directory the test runs from. Set as a constant
	// so the path appears in error messages even when filepath.Glob
	// returns relative entries.
	corpusDir = "."

	// maxFileSize caps any single fixture file. A 1 MiB ceiling keeps
	// accidental binary commits from breaking CI memory usage. The
	// largest realistic file (phone_number with 500+ fixtures) is
	// well under 100 KiB.
	maxFileSize = 1 << 20 // 1 MiB

	// maxLineLen caps the length of any single fixture line after
	// scanner-level buffering. Inputs longer than this almost
	// certainly indicate a bug in the fixture rather than a useful
	// test case.
	maxLineLen = 64 << 10 // 64 KiB

	// lockFileName is the optional SHA-256 manifest the generator
	// writes. If present, TestMain verifies every fixture file's
	// hash before any subtest runs.
	lockFileName = ".corpus.lock"

	// generatedBanner marks the start of the generator-owned section
	// of a fixture file. Everything below this comment is rewritten
	// by `make corpus-regen`; hand edits are clobbered.
	generatedBanner = "# === generated (do not edit; regenerated by make corpus-regen) ==="
)

// pragma represents the parser configuration carried across a single
// file's fixture lines.
type pragma struct {
	escaped bool   // # corpus: escaped — interpret escape sequences
	unknown string // non-empty when parsePragma saw `# corpus: <unknown>`
}

// TestMain validates the .corpus.lock file (if present) before any
// subtest runs, so stale lock detection fails fast with a single
// clear message rather than cascading per-file errors.
func TestMain(m *testing.M) {
	if err := verifyLock(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Exit(m.Run())
}

// TestCorpus runs every .txt file under tests/corpus/ as its own
// subtest. Each subtest iterates the fixture lines and asserts
// mask.Apply(rule, input) == expected, with t.Errorf on mismatch so
// every failure in a single file surfaces at once.
func TestCorpus(t *testing.T) {
	files, err := safeGlob(corpusDir)
	if err != nil {
		t.Fatalf("glob corpus files: %v", err)
	}
	if len(files) == 0 {
		t.Fatalf("no corpus files found under %s/*.txt", corpusDir)
	}

	for _, path := range files {
		path := path
		rule := ruleNameFromPath(path)
		t.Run(rule, func(t *testing.T) {
			t.Parallel()
			runCorpusFile(t, rule, path)
		})
	}
}

// TestCorpusCompleteness asserts that every registered built-in rule
// has a corresponding fixture file and that every fixture file maps
// to a registered rule. New rules without a corpus file fail here;
// orphaned corpus files fail here too.
func TestCorpusCompleteness(t *testing.T) {
	files, err := safeGlob(corpusDir)
	if err != nil {
		t.Fatalf("glob corpus files: %v", err)
	}

	have := make(map[string]bool, len(files))
	for _, p := range files {
		have[ruleNameFromPath(p)] = true
	}

	want := make(map[string]bool)
	for _, name := range mask.Rules() {
		want[name] = true
	}

	// Missing fixture files for registered rules.
	missing := []string{}
	for name := range want {
		if !have[name] {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)
	for _, name := range missing {
		t.Errorf("rule %q has no corpus file — create tests/corpus/%s.txt", name, name)
	}

	// Orphan fixture files with no matching rule.
	orphans := []string{}
	for name := range have {
		if !want[name] {
			orphans = append(orphans, name)
		}
	}
	sort.Strings(orphans)
	for _, name := range orphans {
		t.Errorf("corpus file %s.txt does not correspond to any registered rule", name)
	}
}

// TestCorpusFormatStrict walks every file and validates the byte-level
// invariants: UTF-8, LF line endings (no bare CR), no BOM, no fixture
// line with two or more tabs (which would indicate a tab character
// inside an input or expected field — forbidden by the format spec).
func TestCorpusFormatStrict(t *testing.T) {
	files, err := safeGlob(corpusDir)
	if err != nil {
		t.Fatalf("glob corpus files: %v", err)
	}
	for _, path := range files {
		path := path
		t.Run(filepath.Base(path), func(t *testing.T) {
			t.Parallel()
			body, err := safeReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", path, err)
			}
			if !utf8.Valid(body) {
				t.Errorf("%s: not valid UTF-8", path)
			}
			if len(body) >= 3 && body[0] == 0xEF && body[1] == 0xBB && body[2] == 0xBF {
				t.Errorf("%s: starts with UTF-8 BOM — strip it", path)
			}
			lineNo := 0
			sc := bufio.NewScanner(strings.NewReader(string(body)))
			sc.Buffer(make([]byte, maxLineLen), maxLineLen)
			for sc.Scan() {
				lineNo++
				line := sc.Text()
				if strings.HasSuffix(line, "\r") {
					t.Errorf("%s:%d: trailing CR — use LF line endings only", path, lineNo)
				}
				trim := strings.TrimSpace(line)
				if trim == "" || strings.HasPrefix(trim, "#") {
					continue
				}
				if strings.Count(line, "\t") > 1 {
					t.Errorf("%s:%d: more than one tab — fixture has at most one tab separator", path, lineNo)
				}
			}
			if err := sc.Err(); err != nil {
				t.Errorf("%s: scanner error: %v", path, err)
			}
		})
	}
}

// TestCorpusLockCompleteness asserts that every .txt fixture file
// has a corresponding entry in .corpus.lock. Without this, a
// contributor who adds a new fixture file but forgets to regenerate
// the lock would leave the new file unverified at TestMain time —
// verifyLock only walks listed entries, so omissions are silent.
func TestCorpusLockCompleteness(t *testing.T) {
	t.Parallel()
	files, err := safeGlob(corpusDir)
	if err != nil {
		t.Fatalf("glob corpus files: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(corpusDir, lockFileName))
	if os.IsNotExist(err) {
		t.Skipf("%s does not exist — opt-in lock file is absent", lockFileName)
	}
	if err != nil {
		t.Fatalf("read %s: %v", lockFileName, err)
	}
	listed := make(map[string]bool)
	sc := bufio.NewScanner(strings.NewReader(string(body)))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "  ", 2)
		if len(parts) == 2 {
			listed[parts[1]] = true
		}
	}
	for _, p := range files {
		base := filepath.Base(p)
		if !listed[base] {
			t.Errorf("%s: not listed in %s — run `make corpus-regen` and commit", base, lockFileName)
		}
	}
}

// TestCorpusUnknownRule is a defensive sanity check: applying a rule
// name that is definitely not registered must return FullRedactMarker,
// not echo the input. If this fails, the corpus's "unknown rule
// fail-closed" assumption is broken.
func TestCorpusUnknownRule(t *testing.T) {
	t.Parallel()
	const unknown = "zz_unknown_rule_for_corpus_only"
	if mask.HasRule(unknown) {
		t.Fatalf("test prerequisite violated: %q is registered", unknown)
	}
	got := mask.Apply(unknown, "anything")
	if got != mask.FullRedactMarker {
		t.Errorf("unknown rule must return %q, got %q", mask.FullRedactMarker, got)
	}
}

// runCorpusFile reads one fixture file, parses its lines, and asserts
// each fixture's mask.Apply output. Failures use t.Errorf so the full
// list surfaces in one run.
func runCorpusFile(t *testing.T, rule, path string) {
	t.Helper()

	body, err := safeReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	var pr pragma
	sc := bufio.NewScanner(strings.NewReader(string(body)))
	sc.Buffer(make([]byte, maxLineLen), maxLineLen)
	lineNo := 0
	passed, failed, total := 0, 0, 0

	for sc.Scan() {
		lineNo++
		raw := strings.TrimRight(sc.Text(), "\r")

		// Comments and blank lines.
		trim := strings.TrimSpace(raw)
		switch {
		case trim == "":
			continue
		case strings.HasPrefix(trim, "#"):
			if p, ok := parsePragma(trim); ok {
				if p.unknown != "" {
					t.Errorf("%s:%d: unknown pragma `# corpus: %s` — fix the typo or remove it",
						path, lineNo, p.unknown)
					continue
				}
				pr = p
			}
			continue
		}

		// Fixture line. Must contain a tab.
		tab := strings.IndexByte(raw, '\t')
		if tab < 0 {
			t.Errorf("%s:%d: missing tab separator: %q", path, lineNo, raw)
			failed++
			total++
			continue
		}
		input := raw[:tab]
		expected := raw[tab+1:]

		if pr.escaped {
			decoded, err := decodeEscapes(input)
			if err != nil {
				t.Errorf("%s:%d: input escape: %v", path, lineNo, err)
				failed++
				total++
				continue
			}
			input = decoded

			decoded, err = decodeEscapes(expected)
			if err != nil {
				t.Errorf("%s:%d: expected escape: %v", path, lineNo, err)
				failed++
				total++
				continue
			}
			expected = decoded
		}

		got := mask.Apply(rule, input)
		total++

		// Invariant first: every rule output is valid UTF-8. Asserted
		// before the equality check so that a torn-UTF-8 output is
		// surfaced even on a fixture that happens to match the same
		// torn bytes in expected.
		if !utf8.ValidString(got) {
			t.Errorf("%s:%d: rule %s produced invalid UTF-8 for input %q: % x",
				path, lineNo, rule, input, []byte(got))
		}
		if got != expected {
			t.Errorf("%s:%d:\n  rule:  %s\n  input: %q\n  want:  %q\n  got:   %q",
				path, lineNo, rule, input, expected, got)
			failed++
			continue
		}
		passed++
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("%s: scanner error: %v", path, err)
	}

	t.Logf("corpus %s: %d passed, %d failed (total %d)", rule, passed, failed, total)
	if total == 0 {
		t.Errorf("%s: file contained no test cases — add at least one fixture or delete the file", path)
	}
}

// ruleNameFromPath derives the rule name from a fixture file path.
// "tests/corpus/phone_number.txt" → "phone_number". A future "_extra"
// suffix is stripped so a rule can split its corpus across multiple
// files (e.g. phone_number.txt + phone_number_extra.txt). Today only
// the bare form is used.
func ruleNameFromPath(path string) string {
	stem := strings.TrimSuffix(filepath.Base(path), ".txt")
	return strings.TrimSuffix(stem, "_extra")
}

// safeGlob lists fixture files under dir, rejecting symlinks and any
// file larger than maxFileSize. The size check happens here so the
// rejection surfaces once during discovery rather than once per call
// site of os.ReadFile.
func safeGlob(dir string) ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.txt"))
	if err != nil {
		return nil, err
	}
	out := matches[:0]
	for _, p := range matches {
		info, err := os.Lstat(p)
		if err != nil {
			return nil, fmt.Errorf("lstat %s: %w", p, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("%s: symlinks are not allowed in corpus", p)
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("%s: not a regular file", p)
		}
		if info.Size() > maxFileSize {
			return nil, fmt.Errorf("%s: file size %d exceeds %d-byte cap", p, info.Size(), maxFileSize)
		}
		out = append(out, p)
	}
	sort.Strings(out)
	return out, nil
}

// safeReadFile reads a fixture file with the file-size cap enforced.
// The cap is also checked in safeGlob; this is belt-and-braces in
// case a file is replaced between glob and read.
func safeReadFile(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s: symlinks are not allowed", path)
	}
	if info.Size() > maxFileSize {
		return nil, fmt.Errorf("%s: file size %d exceeds %d-byte cap", path, info.Size(), maxFileSize)
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return io.ReadAll(io.LimitReader(f, maxFileSize+1))
}

// parsePragma recognises pragma comments. Pragmas are lines whose
// trimmed form starts with `# corpus:`. Unknown pragma names are
// reported via the bool return — runCorpusFile turns that into a
// test failure rather than treating it as a benign comment. A typo
// like `# corpus: escaepd` would otherwise become a silent no-op.
func parsePragma(trim string) (pragma, bool) {
	const pfx = "# corpus:"
	if !strings.HasPrefix(trim, pfx) {
		return pragma{}, false
	}
	rest := strings.TrimSpace(strings.TrimPrefix(trim, pfx))
	switch rest {
	case "escaped":
		return pragma{escaped: true}, true
	}
	return pragma{unknown: rest}, true
}

// decodeEscapes interprets the escape sequences \\, \t, \n, \r,
// \xNN, and \uXXXX. Truncated or malformed escapes return an error
// with the byte offset of the failure. Lone UTF-16 surrogates
// (\uD800–\uDFFF) are rejected — they are not legal in Go UTF-8
// strings and would corrupt the mask.Apply input.
func decodeEscapes(s string) (string, error) {
	if !strings.ContainsRune(s, '\\') {
		return s, nil
	}
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); {
		c := s[i]
		if c != '\\' {
			b.WriteByte(c)
			i++
			continue
		}
		// Escape sequence starts at i.
		if i+1 >= len(s) {
			return "", fmt.Errorf("col %d: trailing backslash with no escape character", i+1)
		}
		switch s[i+1] {
		case '\\':
			b.WriteByte('\\')
			i += 2
		case 't':
			b.WriteByte('\t')
			i += 2
		case 'n':
			b.WriteByte('\n')
			i += 2
		case 'r':
			b.WriteByte('\r')
			i += 2
		case 'x':
			if i+3 >= len(s) {
				return "", fmt.Errorf("col %d: truncated \\x escape (needs 2 hex digits)", i+1)
			}
			byteVal, err := hex.DecodeString(s[i+2 : i+4])
			if err != nil {
				return "", fmt.Errorf("col %d: malformed \\x escape %q: %v", i+1, s[i+2:i+4], err)
			}
			// Reject \xNN for NN >= 0x80 — a raw high byte produces
			// invalid UTF-8 in the assembled input string, breaking
			// the library-wide UTF-8 invariant. Authors who need
			// non-ASCII characters use \uXXXX.
			if byteVal[0] >= 0x80 {
				return "", fmt.Errorf("col %d: \\x%02X is not a 7-bit ASCII byte; use \\uXXXX for non-ASCII", i+1, byteVal[0])
			}
			b.WriteByte(byteVal[0])
			i += 4
		case 'u':
			if i+5 >= len(s) {
				return "", fmt.Errorf("col %d: truncated \\u escape (needs 4 hex digits)", i+1)
			}
			cp, err := decodeHex16(s[i+2 : i+6])
			if err != nil {
				return "", fmt.Errorf("col %d: malformed \\u escape %q: %v", i+1, s[i+2:i+6], err)
			}
			if cp >= 0xD800 && cp <= 0xDFFF {
				return "", fmt.Errorf("col %d: lone surrogate \\u%04X is not legal in UTF-8 strings", i+1, cp)
			}
			b.WriteRune(rune(cp))
			i += 6
		default:
			return "", fmt.Errorf("col %d: unknown escape sequence \\%c", i+1, s[i+1])
		}
	}
	return b.String(), nil
}

// decodeHex16 parses a 4-character hex string into an integer.
func decodeHex16(s string) (int, error) {
	if len(s) != 4 {
		return 0, fmt.Errorf("expected 4 hex digits, got %d", len(s))
	}
	var v int
	for i := 0; i < 4; i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9':
			v = v<<4 | int(c-'0')
		case c >= 'a' && c <= 'f':
			v = v<<4 | int(c-'a'+10)
		case c >= 'A' && c <= 'F':
			v = v<<4 | int(c-'A'+10)
		default:
			return 0, fmt.Errorf("non-hex character %q at position %d", c, i)
		}
	}
	return v, nil
}

// verifyLock reads .corpus.lock (if present) and compares the
// recorded SHA-256 of every listed file against the file's current
// hash. The lock file format is one entry per line:
//
//	<hex-sha256>  <filename>
//
// (two spaces, matching the standard `sha256sum` output). Lines
// starting with `#` and blank lines are ignored.
//
// If the lock file does not exist, verifyLock is a no-op — the lock
// is opt-in. The generator writes it; contributors may opt out by
// deleting it.
func verifyLock() error {
	body, err := os.ReadFile(filepath.Join(corpusDir, lockFileName))
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", lockFileName, err)
	}
	sc := bufio.NewScanner(strings.NewReader(string(body)))
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "  ", 2)
		if len(parts) != 2 {
			return fmt.Errorf("%s:%d: malformed entry (expected `<sha256>  <filename>`): %q",
				lockFileName, lineNo, line)
		}
		want, name := parts[0], parts[1]
		got, err := sha256File(filepath.Join(corpusDir, name))
		if err != nil {
			return fmt.Errorf("%s:%d: %w", lockFileName, lineNo, err)
		}
		if got != want {
			return fmt.Errorf("%s:%d: drift for %s (want %s, got %s) — run `make corpus-regen` and commit the result",
				lockFileName, lineNo, name, want, got)
		}
	}
	return sc.Err()
}

// sha256File returns the hex-encoded SHA-256 of a file's contents.
func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}
